language: perl
sudo: false
perl:
  - "5.8"
  - "5.10"
  - "5.16"
  - "5.28"
install:
  - curl -fsSL --compressed https://git.io/cpm | perl - install -g --with-develop --with-recommends
script:
  - perl Build.PL && ./Build && PERL_DL_NONLAZY=1 prove -b t
